# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def prefer_bundler_in_manifest_lock_message(installer)
  installer.aggregate_targets
    .map(&:user_project)
    .compact
    .uniq
    .each do |project|
      changed = false

      project.targets.each do |target|
        target.shell_script_build_phases.each do |phase|
          next unless phase.name == '[CP] Check Pods Manifest.lock'

          unbundled_message = ["Run 'pod", "install'"].join(' ')
          bundled_message = ["Run 'bundle exec pod", "install'"].join(' ')
          next unless phase.shell_script.include?(unbundled_message)

          phase.shell_script = phase.shell_script.gsub(
            unbundled_message,
            bundled_message
          )
          changed = true
        end
      end

      project.save if changed
    end
end

target 'ReactNativeNativeIntegration' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end

post_integrate do |installer|
  prefer_bundler_in_manifest_lock_message(installer)
end
